{% set name = "click-repl" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd12f68d745bf6151210790540b4cb064c7b13e571bc64b6957d98d120dacfd8

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - click
    - prompt_toolkit
    - python >=3.6
    - six

test:
  imports:
    - click_repl

about:
  home: https://github.com/untitaker/click-repl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: REPL plugin for Click
  description: |
    click-repl turns a click-based application into a REPL, enabling
    multiple commands to be executed in single session, with a single
    shared context. Supports tab completion and command history.

extra:
  recipe-maintainers:
    - mcg1969
    - izahn
